version: "3.3"

services:
  postgres:
    restart: always
    container_name: "postgres"
    image: postgres
    environment:
      - POSTGRES_USER=dgmota
      - POSTGRES_PASSWORD=dgmota
      - POSTGRES_DB=prisma
    ports:
      - "5432:5432"
